export const INITIAL_CARDS: string[] = [

"Leonardo DiCaprio",
"Taylor Swift",
"Brad Pitt",
"Shakira",
"Tom Cruise",
"Will Smith",
"Lady Gaga",
"Mickey Mouse",
"Bob Marley",
"Albert Einstein",
"Marilyn Monroe",

"Vincent van Gogh",
"Martin Luther King",
"Sherlock Holmes",
"Hércules",
"Gandhi",
"Drácula",
"Frankenstein",
"Romeo y Julieta",
"Alicia en el País de las Maravillas",
"El Mago de Oz",
"Michael Jackson",
"Madonna",
"Beyoncé",
"Elvis Presley",
"Freddie Mercury",
"Walt Disney",
"Steven Spielberg",
"Alfred Hitchcock",
"Quentin Tarantino",
"George Lucas",
"Ferrari",
"J.K. Rowling",
"Agatha Christie",
"Michael Jordan",
"Roger Federer",
"Rafael Nadal",
"Lionel Messi",
"Cristiano Ronaldo",
"Pelé",
"Diego Maradona",
"Tiger Woods",
"Usain Bolt",
"Mike Tyson",
"Floyd Mayweather",
"David Beckham",
"Zinedine Zidane",
"Ronaldinho",
"Julio César",
"Marie Curie",
"Isaac Newton",
"Nikola Tesla",
"Darwin",
"Alexander Fleming",
"Stephen Hawking",
"Thomas Edison",
"Neil Armstrong",
"Cleopatra",
"Leonardo da Vinci",
"Napoleón Bonaparte",
"Shakespeare",
"Che Guevara",
"Pablo Picasso",
"Beethoven",
"Marie Antoinette",
"Abraham Lincoln",
"Marco Polo",
"Juana de Arco",
"Galileo Galilei",
"Karl Marx",
"Pablo Neruda",
"Casablanca",
"El Padrino",
"Star Wars",
"Titanic",
"El Señor de los Anillos",
"Harry Potter",
"Jurassic Park",
"Avatar",
"La La Land",
"Pulp Fiction",
"Regreso al Futuro",
"Indiana Jones",
"Forrest Gump",
"Gladiador",
"Los Vengadores",
"El Rey León",
"Aladdín",
"Toy Story",
"Matrix",
"Jurassic World",
"Inception",
"Coco",
"El Club de la Lucha",
"Wall-E",
"El Gran Hotel Budapest",
"Los Miserables",
"El exorcista",
"Chinatown",
"Rocky",
"Alien",
"Cazafantasmas",
"Karate Kid",
"Batman",
"Pretty Woman",
"Bailando con Lobos",
"El Silencio de los Corderos",
"En busca de la felicidad",
"El discurso del Rey",
"La vida de Pi",
"El renacido",
"Parásitos",
"Don Quijote de la Mancha",
"Cien años de soledad",
"El Principito",
"Matar a un ruiseñor",
"El Hobbit",
"La Odisea",
"Los Juegos del Hambre",
"La Divina Comedia",
"Crimen y Castigo",
"Guerra y Paz",
"El guardián entre el centeno",
"Viaje al centro de la Tierra",
"La vuelta al mundo en 80 días",
"Robinson Crusoe",
"La isla del tesoro",
"La Iliada",
"El Paraíso Perdido",
"Grandes Esperanzas",
"Un Cuento de Navidad",
"La Metamorfosis",
"El Proceso",
"En el camino",
"Al faro",
"Los Hijos de la Medianoche",
"El Nombre de la Rosa",
"Los Pilares de la Tierra",
"La Sombra del Viento",
"El Código Da Vinci",
"Ángeles y Demonios",
"El Niño con el Pijama de Rayas",
"La Chica del Tren",
"Los hombres que no amaban a las mujeres",
"El Alquimista",
"Cometas en el Cielo",
"La Casa de los Espíritus",
"Minions"
];
